### ISSUE TITLE
Requirement - what version of Construct?

### ISSUE THREAD

**Issue by mungewell** [BastiTee/akai-mpkmini-mkii-control#1]
I know from experience that recent versions of Construct have dropped it's 'embedded' function, you should probably confirm which version is required for your project...

```
simon@thevoid:~/akai-mpkmini-mkii-control-github$ python3 build/lib/akai_mpkmini_mkii_ctrl/mpkmini_mk2.py 
Traceback (most recent call last):
  File "build/lib/akai_mpkmini_mkii_ctrl/mpkmini_mk2.py", line 5, in <module>
    from construct import (Array, Byte, Computed, Const, Default, Embedded, Enum,
ImportError: cannot import name 'Embedded'
```

**Comment by BastiTee** [comment]
Hey @mungewell Good point but I've actually pinned the version in the Pipfile. See: https://github.com/BastiTee/akai-mpkmini-mkii-control/blob/e4a821d3348bf78195015e865f28a87e6090b571/Pipfile#L28

I had the same issue before and therefore set it to `2.9.52`.

How do you install it?

**Comment by mungewell** [comment]
I didn't technically install it, I used `python3 setup.py build` and then ran it from the `build` directory.

Maybe setup tools quirks when you do such things, but I definitely don't have Construct v2.9.52 installed ;-). You should probably set a range, not a specific version.

I might look at updating/removing the embedded stuff, easy enough to deal with an addition Struct/Seq level in the data.

**Comment by mungewell** [comment]
https://github.com/BastiTee/akai-mpkmini-mkii-control/blob/e4a821d3348bf78195015e865f28a87e6090b571/setup.py#L44

**Comment by BastiTee** [comment]
I've set it to a range https://github.com/BastiTee/akai-mpkmini-mkii-control/commit/bad49f2dcbeb0a57b9c241865f03e81b07821fb0

2.10 is the version where the `construct` team removed the Embedded support ([see](https://construct.readthedocs.io/en/latest/transition210.html)).

Let me know if you can update the MPKmini on your end now.

**Comment by mungewell** [comment]
I tried again, same thing without installing

```
simon@thevoid:~/akai-mpkmini-mkii-control-github$ python3 build/lib/akai_mpkmini_mkii_ctrl/ 
__init__.py        __main__.py        controller.py      json_converter.py  mpkmini_mk2.py     note_converter.py
simon@thevoid:~/akai-mpkmini-mkii-control-github$ python3 build/lib/akai_mpkmini_mkii_ctrl/mpkmini_mk2.py 
Traceback (most recent call last):
  File "build/lib/akai_mpkmini_mkii_ctrl/mpkmini_mk2.py", line 5, in <module>
    from construct import (Array, Byte, Computed, Const, Default, Embedded, Enum,
ImportError: cannot import name 'Embedded'
```

However, if I actually install it (not done before) I see that setup tools finds and installs an '.egg' and after that the app runs OK. The '.egg' is timestamped quite old, so perhaps this has been sitting on my disk for a while...

```
simon@thevoid:~/akai-mpkmini-mkii-control-github$ sudo python3 setup.py install
[sudo] password for simon: 

...

Using /usr/lib/python3/dist-packages
Searching for construct==2.9.45
Best match: construct 2.9.45
Processing construct-2.9.45-py3.6.egg
Removing construct 2.10.58 from easy-install.pth file
Adding construct 2.9.45 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg
Searching for click==7.1.2
Best match: click 7.1.2
Adding click 7.1.2 to easy-install.pth file

Using /home/simon/.local/lib/python3.6/site-packages
Finished processing dependencies for akai-mpkmini-mkii-ctrl==0.0.1

simon@thevoid:~/akai-mpkmini-mkii-control-github$ python3 build/lib/akai_mpkmini_mkii_ctrl/mpkmini_mk2.py --help
simon@thevoid:~/akai-mpkmini-mkii-control-github$ ls -al /usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg-rw-r--r-- 1 root staff 216132 Oct 24  2019 /usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg
```

I have been using a git banch of Constuct for a while, so maybe my system is just confused as to what's available to setuptools. Now it's...

```
simon@thevoid:~/akai-mpkmini-mkii-control-github$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import construct
>>> print(construct.version)
(2, 9, 45)
>>>
```

I don't know why setup tools would backdate versions, and potentially break already installed applications. But that's not really your fault. ;-)

**Comment by BastiTee** [comment]
Thanks @mungewell for the detailled feedback. The question remains: Were you able to upload patches to your MPKmini afterall? :) I was really hoping for anyone trying it on their end at least once.

**Comment by BastiTee** [comment]
Oh and by the way. I just noticed that you wrote https://github.com/mungewell/mpd-utils in the first place. Many thanks again for open-sourcing this. This was one of the keys to be able to build this in the first place 🙏
